import { UserRole, AccessLevel } from '../types/auth';

export const SCREEN_ACCESS_MATRIX: Record<UserRole, Record<string, AccessLevel>> = {
  'Executive': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'READ_ONLY',
    'Development': 'NO_ACCESS',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'READ_ONLY',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'READ_ONLY',
    'Historical Record': 'READ_ONLY',
  },
  'Project Manager': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'FULL',
    'Design': 'READ_ONLY',
    'Development': 'READ_ONLY',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'READ_ONLY',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'READ_ONLY',
    'Historical Record': 'READ_ONLY',
  },
  'Architect': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'FULL',
    'Development': 'READ_ONLY',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'READ_ONLY',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'NO_ACCESS',
    'Historical Record': 'READ_ONLY',
  },
  'Developer': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'READ_ONLY',
    'Development': 'FULL',
    'API & Contracts': 'FULL',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'NO_ACCESS',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'NO_ACCESS',
    'Historical Record': 'READ_ONLY',
  },
  'QA / Tester': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'READ_ONLY',
    'Development': 'READ_ONLY',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'FULL',
    'Deployment': 'NO_ACCESS',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'NO_ACCESS',
    'Historical Record': 'READ_ONLY',
  },
  'DevOps / Ops': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'NO_ACCESS',
    'Design': 'NO_ACCESS',
    'Development': 'NO_ACCESS',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'NO_ACCESS',
    'Deployment': 'FULL',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'NO_ACCESS',
    'Historical Record': 'READ_ONLY',
  },
  'Security / Compliance': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'READ_ONLY',
    'Development': 'READ_ONLY',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'READ_ONLY',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'NO_ACCESS',
    'Historical Record': 'READ_ONLY',
  },
  'Finance': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'NO_ACCESS',
    'Development': 'NO_ACCESS',
    'API & Contracts': 'NO_ACCESS',
    'Testing & Validation': 'NO_ACCESS',
    'Deployment': 'NO_ACCESS',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'FULL',
    'Historical Record': 'READ_ONLY',
  },
  'Legal': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'NO_ACCESS',
    'Development': 'NO_ACCESS',
    'API & Contracts': 'NO_ACCESS',
    'Testing & Validation': 'NO_ACCESS',
    'Deployment': 'NO_ACCESS',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'FULL',
    'Historical Record': 'READ_ONLY',
  },
  'Auditor': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'READ_ONLY',
    'Development': 'READ_ONLY',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'READ_ONLY',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'READ_ONLY',
    'Historical Record': 'READ_ONLY',
  },
  'Viewer': {
    'Project Identity': 'READ_ONLY',
    'Requirements': 'READ_ONLY',
    'Design': 'READ_ONLY',
    'Development': 'READ_ONLY',
    'API & Contracts': 'READ_ONLY',
    'Testing & Validation': 'READ_ONLY',
    'Deployment': 'READ_ONLY',
    'Governance & Control': 'READ_ONLY',
    'Financial & Legal': 'NO_ACCESS',
    'Historical Record': 'READ_ONLY',
  },
};

